baseURL = ''
languageCode = 'zh-cn'
title = 'Yuying Wu'
summaryLength = 25
theme = 'fruhling'
defaultcontentlanguage = 'zh'
languagecode = "zh-cn"
enableRobotsTXT = true
googleAnalytics = "UA-74424222-4"
timeout = "1800s"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    robots_txt_disallow_all = false