baseURL = 'http://localhost:8000'
languageCode = 'en-us'
title = 'Yuying Wu'
summaryLength = 25
theme = 'fruhling'
defaultcontentlanguage = 'zh'
languagecode = "en-us"
enableRobotsTXT = true
googleAnalytics = "???"
timeout = "1800s"
remark_enabled = false

[markup.goldmark.renderer]
  unsafe= true

[params]
  robots_txt_disallow_all = false