[zh]
    title = 'Yuying Wu'
    weight = 1
[en]
    title = 'Yuying Wu'
    weight = 2

[[zh.menu.main]]
    name = "旅行"
    weight = 100
    identifier = "blog-travel"
    url = "/tags/travel"
[[zh.menu.main]]
    name = "工作"
    weight = 200
    identifier = "blog-work"
    url = "/tags/work"
[[zh.menu.main]]
    name = "图库"
    weight = 300
    identifier = "gallery"
    url = "/gallery"
# 暂时隐藏英文切换选项
#[[zh.menu.main]]
#    name = "en"
#    identifier = "en"
#    weight = 1000
#    url = "/en"

[[en.menu.main]]
    name = "Travel"
    weight = 100
    identifier = "blog-travel"
    url = "/en/tags/travel"
[[en.menu.main]]
    name = "Work"
    weight = 200
    identifier = "blog-work"
    url = "/en/tags/work"
[[en.menu.main]]
    name = "Photogalleries"
    weight = 300
    identifier = "gallery"
    url = "/en/gallery"
[[en.menu.main]]
    name = "中文"
    identifier = "zh"
    weight = 1000
    url = "/"
